#! /usr/bin/bash

read -p "What compression quality would you like when converting images to webp? " quality_level

mkdir ../webp

for img in *; do
    cwebp -q $quality_level -af -m 6 $img -o "${img%.*}.webp"
done

mv *.webp ../webp