#! /usr/bin/bash

read -p "What compression quality would you like when converting images to webp? " quality_level

for img in *; do
    cwebp -q $quality_level -af -m 6 $img -o "${img%.*}.webp"
done

# Check if parent dir "webp" does not exist (if not, make new dir)
if [[ ! -d "../webp" ]]; then
    mkdir "../webp"
fi

mv *.webp "../webp"