#!/usr/bin/env bash

read -rp "What compression quality would you like when converting images to webp? (0-100) " quality_level

for img in *; do
    cwebp -q "$quality_level" -af -m 6 "$img" -o "${img%.*}.webp"
done

# Check if parent dir "webp" does not exist (if not, make new dir)
if [ ! -d "../webp" ]; then
    mkdir "../webp"
fi

mv *.webp "../webp"